### ISSUE TITLE
switch camera(back/front) in android webrtc is solved by setting facingMode.

### ISSUE THREAD

**Issue by yogurt0713** [telepresence-platform/cocosoco#13]
android 端末でカメラのスイッチングができない問題，webrtcでaudio, videoのmedia streamを生成する際のメソッド
MediaDevices.getUserMedia(constraints)のconstraintsに
{ audio: true, video: { facingMode: "user" } }　/*in case of front camera*/
{ audio: true, video: { facingMode: "environment" } } /*in case of back camera*/
を設定すると切り替えができる

https://developer.mozilla.org/ja/docs/Web/API/MediaDevices/getUserMedia
*上記サイトではenvironment設定の時にexact:"environment"になっているが，exact:なしで大丈夫そう

**Comment by dadaa** [comment]
ラップトップで web cam とかが接続されている場合、どんな感じなるのかなぁ。

**Comment by yogurt0713** [comment]
カメラが1つの場合，userでアクセスできてenvironmentは無効になるみたいです

**Comment by yogurt0713** [comment]
上記，考えてみたのですが，カメラのスイッチングができない問題はandroid端末だけなので
ブラウザがandroidからアクセスされている場合facingModeを指定するという条件分岐の書き方はできないでしょうか

**Comment by dadaa** [comment]
https://github.com/telepresence-platform/cocosoco/blob/2a1fa41ce6a842a5e9ab0475dc6e9fec484c896c/src/components/Presenter.tsx#L53-L57 な感じで検査できそうなので、条件分岐できそうです。
念の為、この方法がスタンダードなのか、いまいちど、他の WebRTC を使っているプログラムを眺めてみた方が良いかもしれませんねー

**Comment by yogurt0713** [comment]
さらに調べてみました．
https://github.com/philnash/mediadevices-camera-selection

上記repoの解説記事
https://www.twilio.com/blog/2018/04/choosing-cameras-javascript-mediadevices-api.html

getUserMediaのcontraintsをdeviceid or facingmodeで切り替えるという方法のようです．
このサンプル実行してみたところ，android, iphone, PC(USBカメラもつけてみました）でカメラスイッチング問題なくできました．
