### ISSUE TITLE
Streaming screen does not fit to window size of Safari browser.

### ISSUE THREAD

**Issue by yogurt0713** [telepresence-platform/cocosoco#30]
ストリーミングビデオ画像がiPadで実行されたココソコの画面で表示するとスクリーンサイズにフィットしないで小さく表示される．
iPad（第7世代） 2台で同様の現象確認

**Comment by dadaa** [comment]
MacBook Pro OSX 10.14.6 の Safari 14.0.1 でも再現できました。
iPad 買わないで大丈夫そうです :)

**Comment by yogurt0713** [comment]
iphoneだとウィンドウサイズが小さいからわからなかったのでしょうかね．
issue タイトルを修正してみました．

**Comment by dadaa** [comment]
このコンポーネント、zoom とかの制御に https://github.com/prc5/react-zoom-pan-pinch を使っているのですが、これの CSS (height: fit-content) などが我々にとって不具合をもたらしている様子です。

**Comment by yogurt0713** [comment]
なるほど！こちら何か解決策はありますか？autoとかにしたらダメなんですよね．

**Comment by dadaa** [comment]
手元でやってみた感じだと、単純にそこらを削除できれば良さそうなんですけど、どうやってやるかなぁ。。って感じです。
