### ISSUE TITLE
cocosoco map does not show on android firefox.

### ISSUE THREAD

**Issue by yogurt0713** [telepresence-platform/cocosoco#33]
ココソコの地図表示がandroid端末のfirefoxで表示されない

AQUOS sense3 lite
OS名 (android 10)
ブラウザ名 (firefox version 83.1.0)
STR 
participateボタンを押す
位置・カメラマイクの許可をした後にココソコ実行画面が表示

ER
ココソコ実行画面で選択された参加者のカメラ画像をメインに，右下部にgoogle mapが表示される

AR(Actual result 実際の結果)
google mapが指定の位置に表示されない

**Comment by dadaa** [comment]
どのバグかが特定できてないのですけれど、手元で試してみたところ Firefox 84 (現時点で beta 版) 以上で治っているようです。
Firefox 84 のリリースを待って、確認ののちこの Issue を閉めたいと思います。

**Comment by dadaa** [comment]
https://wiki.mozilla.org/Release_Management/Calendar
を見ると 12/15 にリリースされる予定なので、そこで確認します。
