### ISSUE TITLE
Back camera of android phone is not shown when clicking camera switch button.

### ISSUE THREAD

**Issue by yogurt0713** [telepresence-platform/cocosoco#44]
**Describe the bug**
前面・背面切り替えボタンを押しても背面カメラの映像が見えない（切り替わって黒画面になる）
再度押すと前面カメラに戻り映像が表示される

**To Reproduce**
1. カメラ切り替えボタンを押す
2. 前面カメラ映像が消えて黒画面になる

**Expected behavior**
1. カメラ切り替えボタンを押す
2. 前面カメラ映像が消えて背面カメラの映像に切り替わる

**Smartphone (please complete the following information):**
Device: [AQUOS sense3 lite]
OS: [android 10]
Browser [chrome, firefox]
Version [96.0.4240.198, 83.1.0]

**Comment by dadaa** [comment]
現状の cocosoco-dev (https://bit.ly/2IGD9tH) で試してみましたが、手持ちの Pixel 2 では Firefox 83 も 85 も Chrome でも正常に動いているようです。
今一度、確認いただけます？？
