### ISSUE TITLE
Hide video and map toggle button of all participants except for a presenter

### ISSUE THREAD

**Issue by yogurt0713** [telepresence-platform/cocosoco#50]
**Is your feature request related to a problem? Please describe.**
cocosocoプレゼンター以外の参加者の表示画面上のビデオとマップのトグルボタンを非表示にする

**Describe the solution you'd like**
プレゼンター表示された時にビデオ，マップのトグルボタンが表示される．

**Comment by dadaa** [comment]
同様に、左側にプレゼンタ専用ボタン、右に共通ボタンなどとグループで配置するとより理解しやすそう。
