### ISSUE TITLE
Audience can't see Presenter's movie when Audience enter the room after Presenter in case network is "mesh".

### ISSUE THREAD

**Issue by nboufSD** [telepresence-platform/cocosoco#60]
OS名 (MacOS Catalina version 10.15.7 )
ブラウザ名 (chrome versioon 87.0.4280.88)

OS名 (iOS version 1sts 4.2 )
ブラウザ名 (safari versioon 604.1)

STR
networkをmeshに設定する
一人目がroomに入室する
一人目がプレゼンターになる
二人目が入室する

ER
二人目の画面にプレゼンターの映像が流れる
AR
二人目の画面にプレゼンターの映像が流れない

**Comment by dadaa** [comment]
fixed
