### ISSUE TITLE
Display a presenter's icon and total numbers of user in a room

### ISSUE THREAD

**Issue by yogurt0713** [telepresence-platform/cocosoco#77]
ココソコのログインユーザー表示インタフェースの改良

画面左（足跡ボタンの左側）に
1．円の中に部屋に参加したユーザー人数を表示
（この表示はギャラリービューとプレゼンタービューが実装された場合のギャラリービューの時に使用）

2．プレゼンターボタンを押した後，
円の中にプレゼンターアイコンと部屋に参加したユーザー人数を表示
（この表示はギャラリービューとプレゼンタービューが実装された場合のプレゼンタービューの時に使用）

**Comment by nboufSD** [comment]
今はギャラリーボタンの部分がmergeされていないのですが、これはこのまま僕の修正をしても宜しい感じでしょうか？
