### ISSUE TITLE
Camera rotation is not correct when ipad is set horizontal mode immediately after starting up iPad.

### ISSUE THREAD

**Issue by yogurt0713** [telepresence-platform/cocosoco#83]
iPad端末を横向きにしてココソコに接続した時にカメラの向きがあっていない（横向きになっていない）
症状が起こるのがiPadを立ち上げた最初に起こり､その後は症状が出ない

**To Reproduce**
1.iPadを横向きにセット
2. ココソコを開く
3. カメラが縦向き方向のカメラ向きなので，顔が横に映る

（一度iPadを縦向きにしてから横向きにすると表示されるカメラ画像は正常な向きになる）

**Expected behavior**
1.iPadを横向きにセット
2. ココソコを開く
3. カメラの映像が端末の向きにそってきちんと映る

**Comment by dadaa** [comment]
fixed
